### ISSUE TITLE
Lambda fails due to 401 Unauthorized Response

### ISSUE THREAD

**Issue by chrisdodds** [aws-samples/amazon-eks-node-drainer#4]
**Context**:
- Region: us-east-1
- k8s version: 1.10

**Expected behavior**:
Node gets autoscaled down, lifecycle hook triggers Lambda function, pods drain from node

**Actual behavior**:
Node gets autoscaled down, lifecycle hook triggers Lambda function, function fails with the following trace:

```START RequestId: cb9a6c5c-b738-41c8-99d7-5e094ed4bf15 Version: $LATEST
[INFO]	2019-04-12T02:43:48.640Z	cb9a6c5c-b738-41c8-99d7-5e094ed4bf15	No kubeconfig file found. Generating...

[INFO]	2019-04-12T02:43:49.252Z	cb9a6c5c-b738-41c8-99d7-5e094ed4bf15	Node name: ip-10-4-5-65.ec2.internal
[ERROR]	2019-04-12T02:43:49.548Z	cb9a6c5c-b738-41c8-99d7-5e094ed4bf15	There was an error removing the pods from the node ip-10-4-5-65.ec2.internal
Traceback (most recent call last):
File "/var/task/handler.py", line 137, in _lambda_handler
if not node_exists(v1, node_name):
File "/var/task/k8s_utils.py", line 47, in node_exists
nodes = api.list_node(include_uninitialized=True, pretty=True).items
File "/var/task/kubernetes/client/apis/core_v1_api.py", line 13392, in list_node
(data) = self.list_node_with_http_info(**kwargs)
File "/var/task/kubernetes/client/apis/core_v1_api.py", line 13489, in list_node_with_http_info
collection_formats=collection_formats)
File "/var/task/kubernetes/client/api_client.py", line 334, in call_api
_return_http_data_only, collection_formats, _preload_content, _request_timeout)
File "/var/task/kubernetes/client/api_client.py", line 168, in __call_api
_request_timeout=_request_timeout)
File "/var/task/kubernetes/client/api_client.py", line 355, in request
headers=headers)
File "/var/task/kubernetes/client/rest.py", line 231, in GET
query_params=query_params)
File "/var/task/kubernetes/client/rest.py", line 222, in request
raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '674797e4-c6a2-4757-b2b5-f613ee0b9768', 'Content-Type': 'application/json', 'Date': 'Fri, 12 Apr 2019 02:43:49 GMT', 'Content-Length': '165'})
HTTP response body: {
"kind": "Status",
"apiVersion": "v1",
"metadata": {

},
"status": "Failure",
"message": "Unauthorized",
"reason": "Unauthorized",
"code": 401
}
END RequestId: cb9a6c5c-b738-41c8-99d7-5e094ed4bf15
REPORT RequestId: cb9a6c5c-b738-41c8-99d7-5e094ed4bf15	Duration: 1306.67 ms	Billed Duration: 1400 ms Memory Size: 256 MB	Max Memory Used: 122 MB
```

**What I've done**:
- Confirmed RBAC setup correctly per README
- Confirmed cluster name and region
- Confirmed aws-auth configmap included the correct lambda arn and username
- Confirmed IAM permissions and that STS is being called for the bearer token generation
- Confirmed that k8s api is not vpc-only (I would assume no response otherwise)
- Done my best to validate that the returned bearer token is correctly formatted

As best I can guess this is a bearer token issue, but I can't figure out what might be wrong in that regard.

**Comment by svozza** [comment]
Interesting, I have only tested this on Kubernetes 1.11, I wonder if it could be something to do with this. If you look in the code you'll see I had issues with the bearer token (there's a link to a Github issue on the AWS IAM Authenticator in the code). I will try to spin up a 1.10 cluster to see if I can replicate but in the meantime (and this is a long shot) try removing the remediation I made for the bug in the IAM Authenticator and see if that makes a difference:

```python
# change this:
return 'k8s-aws-v1.' + re.sub(r'=*', '', base64_url)
# to this
return 'k8s-aws-v1.' + base64_url
```

**Comment by chrisdodds** [comment]
I just tried:
```
return 'k8s-aws-v1.' + base64_url
```
with the same result.
I also skimmed through the change logs for 1.10 and 1.11 to see if there were any documented changes that might come into play here. The closest I could find were some changes to OIDC, but otherwise didn't see anything specifically related to bearer token processing.

**Comment by svozza** [comment]
That's a shame but it was a long shot. Unfortunately, I have created a 1.10 cluster and deployed the drainer solution and it worked fine for me so I'm a bit at a loss. Can you enable the logging on the Control Plane and see if there's anything interesting in there? The instructions are [here](https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html).

Also, to aid debugging can you paste the output of `kubectl edit -n kube-system configmap/aws-auth`? Remember to redact any sensitive information.

And as a possible workaround while we diagnose this, could you try to give the IAM role more liberal permissions by adding the following when you run the above command:

```yaml
- rolearn: arn:aws:iam::060997615305:role/<Drainer Lambda Role>
  username: EKSForLambda
  groups:
    - system:masters
```

**Comment by chrisdodds** [comment]
Thanks for testing, really appreciate it.

I just figured out the issue and it was a dumb mistake on my part. I went too far down the rabbit hole. I was using the ARN output value from the stack creation, which looks like this:

```arn:aws:lambda:us-east-1:ACCOUNTNUMBER:function:sandbox-k8s-drainer-DrainerFunction-MX5HUMO8F5YM```

I thought that looked odd at the time, but just blindly skimmed past and didn't hone in on it not being a role ARN. I was too stuck in my mental model of what *I* thought the stack output would be.

The actual role ARN looks like an IAM role ARN should:

```arn:aws:iam::ACCOUNTNUMBER:role/sandbox-k8s-drainer-DrainerFunctionRole-1IBBCVLUME890```

**Comment by svozza** [comment]
Ah yes, it's funny I was in too minds as to whether to export that, maybe I should get rid of it because it's confusing and not really relevant. I would have liked to export the role but SAM creates it implicitly so there's no way to reference it in the CloudFormation script. Anyway, glad we got to the bottom of it!
