### ISSUE TITLE
Signal Returned to ASG before pods terminate gracefully.

### ISSUE THREAD

**Issue by tahoward** [aws-samples/amazon-eks-node-drainer#9]
Using k8s 1.11 the evict API endpoint appears to ignore pods that handle SIGTERM gracefully with a generous termination grace period set. Havn't tested other k8s versions yet.

Have had better luck with the delete pod API endpoint and polling pods till they are all terminated. Although this does not respect any pod disruption budgets.

**Comment by matteofigus** [comment]
Hi @tahoward thanks for opening an issue.

Can you quantify `generous termination grace period` is? Just to have an idea.

**Comment by tahoward** [comment]
Been using 60 seconds (default 30). Don't think the grace period matters as long as the time the pod containers take to handle sigterm does not exceed it's value. Looking at pod logs a sigterm does initially get sent when an eviction is created via API. However, the pod is killed well before the sigterm handler completes. This does not happen when using delete pod API endpoint.

**Comment by svozza** [comment]
This appears to be a [bug](https://github.com/kubernetes/kubernetes/pull/72730/) in the eviction API where if you don't provide `delete_options` you get the behaviour you're seeing. It looks like this fix has only made it into the `1.14` branch. There is a workaround detailed in the [issue](https://github.com/kubernetes/kubernetes/issues/72717) where it was reported. Can you change the code in the `k8s_util.py` file to this and see if it fixes the problem:

```python
body = {
            'apiVersion': 'policy/v1beta1',
            'kind': 'Eviction',
            'delete_options': {},
            'metadata': {
                'name': pod.metadata.name,
                'namespace': pod.metadata.namespace
            }
        }
api.create_namespaced_pod_eviction(pod.metadata.name + '-eviction', pod.metadata.namespace, body)
```
I suspect we may end up have to add some code to poll the pods to make sure that pods have been deleted but let's try this first.

**Comment by svozza** [comment]
From my own testing, this didn't seem to work, interested to see what you find.

**Comment by tahoward** [comment]
I replicated your results. ATM I'm using the delete API with a 1 second poller excluding DaemonSet `kind` pods.

**Comment by svozza** [comment]
I think #10 might fix the issues you've encountered here @tahoward .

**Comment by svozza** [comment]
I'm going to close this but feel free to reopen if it doesn't.
